name: ap2_rodrigo
description: "AP2 Rodrigo Costa"
publish_to: 'none'  # Não publicar no pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/padrao.png
    - assets/pedra.png
    - assets/papel.png
    - assets/tesoura.png
    - assets/cara.png
    - assets/coroa.png
    - assets/passarinho.png
